app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

provider:
  github:
    baseUrl: "https://api.github.com"
  stackoverflow:
    baseUrl: "https://api.stackexchange.com/2.3"

spring:
  liquibase:
    change-log: classpath:migrations/master.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5435/scrapper
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  application:
    name: scrapper
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
  default-produces-media-type: application/json

client:
  bot:
    baseUrl: "http://localhost:8090"
