app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

provider:
  github:
    baseUrl: "https://api.github.com"
  stackoverflow:
    baseUrl: "https://api.stackexchange.com/2.3"

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
  default-produces-media-type: application/json

client:
  bot:
    baseUrl: "https://localhost:8090"
